# Generated by Django 4.0 on 2022-04-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charactersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecharacter',
            name='fullImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
